### ISSUE TITLE
Support Android

### ISSUE THREAD

**Issue by azkadev** [flame-engine/gamepads#17]
I'm trying to make a game with flutter + flame, please provide support so I can use a gamepad on Android

**Comment by markvideon** [comment]
I made a relevant comment on another issue late last year [here](https://github.com/flame-engine/gamepads/issues/13#issuecomment-1859535100).

I can't speak for the maintainers of this project but I intend to look into developing a package that extends the gamepads platform interface and uses the GameController Library for Android soon.

**Comment by azkadev** [comment]
> I made a relevant comment on another issue late last year [here](https://github.com/flame-engine/gamepads/issues/13#issuecomment-1859535100).
> 
> I can't speak for the maintainers of this project but I intend to look into developing a package that extends the gamepads platform interface and uses the GameController Library for Android soon.

thanks

**Comment by markvideon** [comment]
Merged!
