### ISSUE TITLE
Cannot compile macOS example,  'sfSymbolsName' is only available in macOS 11.0 or newer

### ISSUE THREAD

**Issue by markvideon** [flame-engine/gamepads#18]
The getValues method in the GamepadsDarwinSwift implementation references sfSymbolsName, but this property is not available for all supported targets. (e.g. it is only available after macOS 11.0)

Other methods in GamepadsDarwinSwift use conditional compilation to avoid similar issues. 

I was able to compile the example project after changing the affected code blocks to make use of conditional compilation.

<details>
<summary>Indicative fix for GamepadsDarwinSwift getValues</summary>

    private func getValues(element: GCControllerElement) -> [(String, Float)] {
        if let element = element as? GCControllerButtonInput {
            var button: String = "Unknown button"
            if #available(macOS 11.0, *) {
                if (element.sfSymbolsName != nil) {
                    button = element.sfSymbolsName!
                }
            }
            
            return [(button, element.value)]
        } else if let element = element as? GCControllerAxisInput {
            var axis: String = "Unknown axis"
            if #available(macOS 11.0, *) {
                if (element.sfSymbolsName != nil) {
                    axis = element.sfSymbolsName!
                }
            }
            return [(axis, element.value)]
        } else if let element = element as? GCControllerDirectionPad {
            var directionPad: String = "Unknown direction pad"

            if #available(macOS 11.0, *) {
                if (element.sfSymbolsName != nil) {
                    directionPad = element.sfSymbolsName!
                }
            }
            return [
                (maybeConcat(directionPad, "xAxis"), element.xAxis.value),
                (maybeConcat(directionPad, "yAxis"), element.yAxis.value)
            ]
        } else {
            return []
        }
    }
</details>

Happy to open a PR with this implementation.

**Comment by gotnull** [comment]
Did you actually get any gamepads to work in MacOS? If so, I'd love to give it a try!

**Comment by gotnull** [comment]
I can confirm I got this working with your fix for the `GamepadsDarwinSwift` class.

**Comment by gotnull** [comment]
> The getValues method in the GamepadsDarwinSwift implementation references sfSymbolsName, but this property is not available for all supported targets. (e.g. it is only available after macOS 11.0)
> 
> Other methods in GamepadsDarwinSwift use conditional compilation to avoid similar issues.
> 
> I was able to compile the example project after changing the affected code blocks to make use of conditional compilation.
> 
> Indicative fix for GamepadsDarwinSwift getValues
> Happy to open a PR with this implementation.

I can confirm I got this working with your fix for the GamepadsDarwinSwift class. You should definitely open a PR with this implementation! :D

**Comment by markvideon** [comment]
PR merged, issue can be closed!
