### ISSUE TITLE
Unhandled Exception: MissingPluginException

### ISSUE THREAD

**Issue by sirbig** [flame-engine/gamepads#21]
When running your example on folder "packages\gamepads\example" with Android Flutter, it installs everything correctly and the app is installed on my Xiamo Mi 10T Lite, but as soon as the app opens and I click on "listGamepads()" it throws the following errors:

```
W/MirrorManager(14339): this model don't Support
E/flutter (14339): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method listGamepads on channel xyz.luan/gamepads)
E/flutter (14339): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
E/flutter (14339): <asynchronous suspension>
E/flutter (14339): #1      MethodChannelGamepadsPlatformInterface.listGamepads (package:gamepads_platform_interface/method_channel_gamepads_platform_interface.dart:19:20)
E/flutter (14339): <asynchronous suspension>
E/flutter (14339): #2      _MyHomePageState._getValue (package:gamepads_example/main.dart:41:22)
E/flutter (14339): <asynchronous suspension>
E/flutter (14339): 
```

Does this mean that my smartphone is not supported for some reason or am I missing something?

Thanks and great project you have going on! 👍

**Comment by markvideon** [comment]
The project does not officially support Android. There is no Android implementation. There is an issue requesting Android support. 

https://github.com/flame-engine/gamepads/issues/17

**Comment by sirbig** [comment]
> The project does not officially support Android. There is no Android implementation. There is an issue requesting Android support.
> 
> #17

Thanks for your reply, hopefully Android will be supported in the future. 👍
