### ISSUE TITLE
List supported platforms

### ISSUE THREAD

**Issue by derrick56007** [flame-engine/gamepads#33]
This package advertises controller support across multiple platforms. Taking a look at the current issues it doesn't seem to work for most platforms...

Which ones are actually supported? Currently not web, android, ios, or macos.. so the only supported system is Windows?

**Comment by markvideon** [comment]
According to pub, it currently supports desktop platforms.

https://pub.dev/packages/gamepads

There is a PR open for iOS support, which is a port of the macOS plugin. I am actively working on an Android version.

**Comment by markvideon** [comment]
You can also see the supported platforms by inspecting the package's pubspec.yaml file. 

https://github.com/flame-engine/gamepads/blob/main/packages/gamepads/pubspec.yaml
