### ISSUE TITLE
Missing plugin exception

### ISSUE THREAD

**Issue by akucherk** [flame-engine/gamepads#38]
Hello.
I launched on real android device the packages\gamepads\example\lib\main.dart but got on Gamepads.list() call:
MissingPluginException (MissingPluginException(No implementation found for method listGamepads on channel xyz.luan/gamepads))

How can I make it works?

**Comment by markvideon** [comment]
> Hello. I launched on real android device the packages\gamepads\example\lib\main.dart but got on Gamepads.list() call: MissingPluginException (MissingPluginException(No implementation found for method listGamepads on channel xyz.luan/gamepads))
> 
> How can I make it works?

Did you modify your application's MainActivity as per the Android integration instructions [in the README](https://github.com/flame-engine/gamepads/blob/main/README.md)?

**Comment by markvideon** [comment]
How are you referencing gamepads in your pubspec.yaml file? The latest published version of gamepads on pub.dev (0.1.1) does not support Android, so if you are depending on gamepads from pub, gamepads_android simply will not be included in your build. 

Everything _should_ be in sync on git at the moment.

**Comment by luanpotter** [comment]
Closing due to lack of response

**Comment by akucherk** [comment]
Hello, thanks for your answer.
I creaed new flutter project, 
- added 'gamepads: ^0.1.1' string to pubspec.yaml
- replace code in main.dart with https://github.com/flame-engine/gamepads/blob/main/packages/gamepads/example/lib/main.dart 
- replace code in MainActivity.kt with mentioned android integration code from readme.md

And got follow in debug console on build:
e: \gamepadtest\android\app\src\main\kotlin\com\example\gamepadtest\MainActivity.kt: (9, 12): Unresolved reference: flame_engine
e: \gamepadtest\android\app\src\main\kotlin\com\example\gamepadtest\MainActivity.kt: (11, 40): Unresolved reference: GamepadsCompatibleActivity
e: \gamepadtest\android\app\src\main\kotlin\com\example\gamepadtest\MainActivity.kt: (23, 5): 'registerInputDeviceListener' overrides nothing
e: \gamepadtest\android\app\src\main\kotlin\com\example\gamepadtest\MainActivity.kt: (29, 5): 'registerKeyEventHandler' overrides nothing
e: \gamepadtest\android\app\src\main\kotlin\com\example\gamepadtest\MainActivity.kt: (33, 5): 'registerMotionEventHandler' overrides nothing

**Comment by markvideon** [comment]
> Hello, thanks for your answer.
> 
> I creaed new flutter project, 
> 
> - added 'gamepads: ^0.1.1' string to pubspec.yaml
> 
> - replace code in main.dart with https://github.com/flame-engine/gamepads/blob/main/packages/gamepads/example/lib/main.dart 
> 
> - replace code in MainActivity.kt with mentioned android integration code from readme.md
> 
> 
> 
> And got follow in debug console on build:
> 
> e: \gamepadtest\android\app\src\main\kotlin\com\example\gamepadtest\MainActivity.kt: (9, 12): Unresolved reference: flame_engine
> 
> e: \gamepadtest\android\app\src\main\kotlin\com\example\gamepadtest\MainActivity.kt: (11, 40): Unresolved reference: GamepadsCompatibleActivity
> 
> e: \gamepadtest\android\app\src\main\kotlin\com\example\gamepadtest\MainActivity.kt: (23, 5): 'registerInputDeviceListener' overrides nothing
> 
> e: \gamepadtest\android\app\src\main\kotlin\com\example\gamepadtest\MainActivity.kt: (29, 5): 'registerKeyEventHandler' overrides nothing
> 
> e: \gamepadtest\android\app\src\main\kotlin\com\example\gamepadtest\MainActivity.kt: (33, 5): 'registerMotionEventHandler' overrides nothing

This interface referred to in the integration code is introduced in gamepads 0.1.2, please upgrade the package, that should resolve the issue.
