### ISSUE TITLE
Button r2 Not all the same

### ISSUE THREAD

**Issue by azkadev** [flame-engine/gamepads#4]
Not all r2 buttons have the same button like this, I tried your library values only at 0.0 and 1.0

Please make it support stick buttons like this.
![](https://venturebeat.com/wp-content/uploads/2013/10/dualshock-4-buttons-and-triggers.jpg?w=1200&strip=all)

Btw Thank you for creating this library

**Comment by spydon** [comment]
Which platform do you get that on? In Linux I get non integer values.

**Comment by azkadev** [comment]
> Which platform do you get that on? In Linux I get non integer values.

i use game pad pxn 9607x on linux

https://www.e-pxn.com/products/game-controller/pxn-9607x

![image](https://github.com/flame-engine/gamepads/assets/82513502/38202901-a1bc-4a55-8df8-21e23f6ac63b)

**Comment by spydon** [comment]
Can you check if the driver is giving you better values?

**Comment by markvideon** [comment]
> Can you check if the driver is giving you better values directly?

A highly relevant question. According to this [link](https://github.com/Electronicks/JoyShockMapper?tab=readme-ov-file#2-analog-triggers), the Switch Pro controller only has a digital trigger. 

> > Which platform do you get that on? In Linux I get non integer values.
> 
> i use game pad pxn 9607x on linux
> 
> https://www.e-pxn.com/products/game-controller/pxn-9607x
> 
> ![image](https://private-user-images.githubusercontent.com/82513502/277719174-38202901-a1bc-4a55-8df8-21e23f6ac63b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3MDkwMjgsIm5iZiI6MTcwMjcwODcyOCwicGF0aCI6Ii84MjUxMzUwMi8yNzc3MTkxNzQtMzgyMDI5MDEtYTFiYy00YTU1LThkZjgtMjFlMjNmNmFjNjNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE2VDA2Mzg0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1M2I3YjhkYTUyYzkzMzg3MmI4ODVhYjZjZWE5NzhiZDIyZmFlNDI5YjVmYWZhMTUzZWI4OTFjZGM0NzFkN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Rs4a4yow-sQSfR0JvUgaQYIgQMRHLEbnJqmK9lyky4s)

According to the link provided, this gamepad is marketed as a Switch Pro controller. It may only be a digital trigger.
