### ISSUE TITLE
[ASK] Why not publish the latest version to the dev pub?

### ISSUE THREAD

**Issue by azkadev** [flame-engine/gamepads#40]
https://pub.dev/packages/gamepads

**Comment by luanpotter** [comment]
@markvideon @spydon any objections to making a release?

**Comment by spydon** [comment]
> @markvideon @spydon any objections to making a release?

Sure, let's do it!
Will you do it?
If you don't remember:
```sh
melos version --no-git-tag-version
<< make PR >>
<< merge PR >>
melos publish -t --no-dry-run
git push --follow-tags
```

**Comment by spydon** [comment]
gamepads v0.1.2 is now released
