### ISSUE TITLE
Request for Enhancing Gamepad Trigger Event Support in Android

### ISSUE THREAD

**Issue by eungyoda** [flame-engine/gamepads#44]
I've been using the gamepads package and it's working well. 

While checking Android events in my ongoing project, I noticed that the analog events for the Left/Right Trigger buttons are not functioning correctly.

The target device I am using is the Retroid Pocket 4 Pro, which runs Android 13. 
This device is a retro gaming console where the Android OS and Gamepad are integrated.

On this device, the AXIS_LTRIGGER and AXIS_RTRIGGER events do not trigger, and instead, the AXIS_BRAKE and AXIS_GAS events generate the analog events for the triggers.

This seems like an oversight from the Chinese developers, or perhaps it’s part of their development philosophy.

In any case, here’s what I’d like to request:

A simple solution would be to add the following to the supportedAxes object in the "EventListener.kt" file:

```
SupportedAxis(MotionEvent.AXIS_BRAKE),
SupportedAxis(MotionEvent.AXIS_GAS),
```

Another suggestion would be to add a function to the gamepads object that allows the modification of supportedAxes so that additional events can be specified or unnecessary events can be removed.

If you have a better approach, please feel free to use that. If not, I hope you consider one of the solutions mentioned above.

I am currently using a modified version locally. If I am granted "Contributors" access, I will submit a pull request with the changes I've made.

Thanks. @all

**Comment by markvideon** [comment]
A reasonable proposal I think. Happy to make the change

**Comment by markvideon** [comment]
Has been actioned and will be in the next release, probably 0.1.5.
