### ISSUE TITLE
No implementation found for method listGamepads

### ISSUE THREAD

**Issue by Welleee** [flame-engine/gamepads#8]
I'm having this error when I want to list all the gamepads.

`Unhandled Exception: MissingPluginException(No implementation found for method listGamepads on channel xyz.luan/gamepads)
`

I already restarted the app, visual studio code and recompile but always the same problem.
I'm using 0.1.1 version of gamepads library and 3.1.0 dart SDK.

Any ideas?

Thanks

**Comment by erickzanardo** [comment]
@Welleee which platform is that happening?

**Comment by Welleee** [comment]
@erickzanardo On android and web browser

**Comment by julianoBRL** [comment]
I'm having the same problem here, new project just created with just this lib installed, current Dart SDK version is 3.1.1, testing on an Android 13 physical device.

@Welleee Did you find any solution or workaround?

**Comment by Welleee** [comment]
@julianoBRL I noticed the plugin is only compatible with Linux, Windows and macOS
