### ISSUE TITLE
【windows】导入了差距之后就不能调整屏幕大小，点击其他应用之后，键盘就不能使用了

### ISSUE THREAD

**Issue by chengwei88888** [flame-engine/gamepads#9]
w导入了差距之后就不能调整屏幕大小，点击其他应用之后，键盘就不能使用了

**Comment by erickzanardo** [comment]
Please, use English for issues.

**Comment by chengwei88888** [comment]
> Please, use English for issues.
After importing the gap, the screen size cannot be adjusted. After clicking on other applications, the keyboard cannot be used anymore

**Comment by spydon** [comment]
Duplicate of #9
